name: gamelog
description: A social platform for gamers to track, rate, and review games - like Letterboxd but for video games!
publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  image_picker: ^1.0.4
  crop_your_image: ^2.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/